### ISSUE TITLE
Get <CR-LF> at the end of a client message

### ISSUE THREAD

**Issue by bjacob-56** [ClemaX/ft_irc#10]
I have a feeling that we can't get the '\r' that is supposed to be at the end of a client message (<CR-LF>).
Should we just  look for a '\n' instead of a "\r\n" ?

For now, I'm using "#define IRC_MESSAGE_SUFFIX "\n"" in the ircdef.hpp file.

**Comment by ClemaX** [comment]
You need to use irc::Server in the main. As well as `--crlf` in the `netcat` flags. For me it is working fine and suffix handler is built in to the irc::Message class.

[Connecting to the Server](../wiki/Connecting-to-the-Server)

**Comment by pablo-lamtenzan** [comment]
There's no reason for '\r' not working. A string is just a aligned collection of integers which an specific size. Just comparing with the numeric values should be enough or perhabs casting the last 2 bytes in a short (2bytes size) and check if this value is == ('\r' << 8) | '\n' is a better/faster way to solve this problem:

```
// C style solution (just need to be adapted to c++)

char msg[512]; // amuse contains data

for (size_t i = 0 ; i < sizeof(msg) ; i++)
    if ((short)msg == (short)(('\r' << 8) | '\n')
         ; // End msg

// Same solution can be achieved in c++ using std::string iterator and creating new messages form the substrings using the range constructor: template <InputIt> std::string::string(InputIt first, InputIt last) or assign.

**Comment by bjacob-56** [comment]
It's working great with the -c option, thanks.
