### ISSUE TITLE
The arguments parsing needs to be adjusted.

### ISSUE THREAD

**Issue by bjacob-56** [ClemaX/ft_irc#16]
When using the TOPIC channel command, you can try `TOPIC <channel> This is the new                 topic`.
This will set `This is the new                 topic` as the topic of <channel>, keeping the string untouched with as many spaces as we want between words.

For now, we split the argument list with spaces as delimiters.

We could :

- Check the command before parsing the arguments to see if he need to keep the whole string as one argument or split it.
- Do and keep two parsing (one splitting argument, the other one with one string as argument) and use the correct one later.
- Keep the current parsing and add an int to each argument (the number of spaces before the argument).

Any better  idea ? What do you think ?

**Comment by ClemaX** [comment]
The protocol specifies that the last(trailing) message can be preceded by semicolon in order to parse phrases containing whitespace.

Someone needs to handle the special semicolon character before parsing any argument (in the parseField command maybe).

**Comment by bjacob-56** [comment]
Ok, the IRC I'm using for testing might have additional features.

Our parsing already handles a colon (IRC_MESSAGE_PREFIX_PREFIX ':', not ';') this way and keep it at the beginning of the argument. Maybe it's enough.

**Comment by ClemaX** [comment]
Sorry, i meant colon and not semicolon. But yes it is used the same way as the prefix IIRC.

**Comment by ClemaX** [comment]
The corresponding reference can be found at 2.3.1 Messages format in pseudocode.
