### ISSUE TITLE
Server Hostname

### ISSUE THREAD

**Issue by ClemaX** [ClemaX/ft_irc#17]
I started adding HOSTNAME parameter to the irc config with a default value of "localhost". I noticed we would use this name very often and am unsure on how to handle it.

Here are the two possibilities:
- Add a global variable
- Add a reference to our irc::Server basically everywhere where we reply to an user

**Comment by ClemaX** [comment]
I chose to add irc::Server references where needed. Fixed by #18 .

**Comment by ClemaX** [comment]
Maybe it is better if we use a global hostname.

**Comment by bjacob-56** [comment]
Not sure what's better, but for now I'm using the SERVER_NAME variable defined in the include file in all the channel replies.

**Comment by pablo-lamtenzan** [comment]
I'll declare in irc/Server.hpp a global mutable std::string been pre-initialized by "localhost" (will be named irc::ServerName , then replace all "SERVER_NAME" defines by this varaible in the code and finally proceed to include irc/Server.hpp in the required files.

**Comment by ClemaX** [comment]
Okay, just set the value in the server constructor. The value can be retrieved using `config[IRC_CONFIG_HOSTNAME]` IIRC.

**Comment by ClemaX** [comment]
I added a global variable gHostname.
