### ISSUE TITLE
Server-Client Welcome Sequence

### ISSUE THREAD

**Issue by ClemaX** [ClemaX/ft_irc#20]
>        001    RPL_WELCOME
>               "Welcome to the Internet Relay Network
>                <nick>!<user>@<host>"
>        002    RPL_YOURHOST
>               "Your host is <servername>, running version <ver>"
>        003    RPL_CREATED
>               "This server was created <date>"
>        004    RPL_MYINFO
>               "<servername> <version> <available user modes>
>                <available channel modes>"
> 
>          - The server sends Replies 001 to 004 to a user upon
>            successful registration.

From [RFC 2812 section 5.1](https://tools.ietf.org/html/rfc2812#section-5.1)

**Comment by pablo-lamtenzan** [comment]
I'll do this

**Comment by pablo-lamtenzan** [comment]
DONE BUT STILL NEED THE TIME OF CREATION OF THE SERVER, THE CHANEL AND USER MODES

**Comment by ClemaX** [comment]
Ok, I will be working on the date string.

**Comment by pablo-lamtenzan** [comment]
DONE
