### ISSUE TITLE
Signal handling (for killer signals)

### ISSUE THREAD

**Issue by pablo-lamtenzan** [ClemaX/ft_irc#23]
The server must be able free it resources while interacting with the kernel signals. For handable signals (all except SIGKILL & SIGSTOP), that will force the process to end (e.g. SIGTERM, SIGHUP), handlers must be implemented. Currently default handler may cause leaks.

Too see:
- Select
- errno EINTR

**Comment by pablo-lamtenzan** [comment]
What you mean by signal id ? The integer taken as first param by signal ? Why you need to store this ?

**Comment by ClemaX** [comment]
The server could be restarted in case of SIGHUP, so it would be useful to know which signal triggered a server-stop.

**Comment by ClemaX** [comment]
Fixed by #27 .
