### ISSUE TITLE
testName and testNick still used on connection

### ISSUE THREAD

**Issue by bjacob-56** [ClemaX/ft_irc#33]
Maybe it's part of the #20 'Server-Client Welcome Sequence' issue.
Client still have a default username and nickname when they connect to the server.

**Comment by ClemaX** [comment]
Yes, the default nickname should be ''*

**Comment by bjacob-56** [comment]
Ok, is it the same for the default username and can a client change it ?

**Comment by ClemaX** [comment]
Now the only thing left to do is update nickname to client map keys after NICK changes..
