### ISSUE TITLE
Set password in command PASS

### ISSUE THREAD

**Issue by pablo-lamtenzan** [ClemaX/ft_irc#36]
I've done what was needed for USER, NICK & PASS. Just i don't know how to use the pass and i can ask u right now (to late). So in PASS.cpp you got a comment to set the pass to whatever it have to be set. Just this need to be done. And when it will to be done i think we end the project. Sorry.

I handled this but just for parctical information, PASS can be called in the following order in freenode:
- PASS, USER, NICK
- PASS, NICK, USER
- USER, PASS, NICK
- NICK, PASS USER

**Comment by ClemaX** [comment]
You do not need to call PASS on freenode, that's why the order does not matter.
PASS is the connection passwords, so it is required to be the first command if the password is enabled.
The ServerConfig contains a PASS key.
