### ISSUE TITLE
bjacob's questions

### ISSUE THREAD

**Issue by bjacob-56** [ClemaX/ft_irc#4]
SocketConnection.hpp
   - "SocketConnection() throw();"
	Quel sens a le throw (pareil pour les autres fonctions du fichiers) ?
   - "inline bool	isOpen() const throw()"
        inline nécessaire ?

SocketServer.hpp
   - "fd_set				connections;"
        Qu'est vraiment fd_set ? Un tableau ?
   - "connectionFds[connectionFd] = connection;"
        Possible d'ajouter un element dans une map de cette facon ?

**Comment by ClemaX** [comment]
- Les throws sans argument sont des "Placeholders". Ils vont faire cracher le programme et signifient qu'il faut implementer un nouveau type d'exception.
(Je l'utilise comme un TODO). En cas normal le throw sans argument n'est valide que dans un try catch, pour "rethrow" l'exception au prochain handler.

**Comment by ClemaX** [comment]
-isOpen nest pas necessaire, mais lidee cest de faire une classe socketconnection qui fonctionne comme les ostream/ofstream (flux/fichier de sorties) et istream/ifstream (flux/fichier d'entrée), qui eu meme implémentent ce genre d'utilitaires booleans

**Comment by ClemaX** [comment]
fd_set est un array de field bitwise (qui contient des integraux utilisé avec des masques et operations binaires) auquel on peut assigner des fd qui doivent etre surveilles. La fonction select vient changer un bit particulier a l'index de chaque fd modifié, ce qui permet de prendre compte les changement grace au macro FD_ISSET.

**Comment by ClemaX** [comment]
- Il est possible d'assigner une connection a la map `connectionFds` (qui devrait plutot s'appeler `connectionMap`), car l'opérateur `map[_]` assigne ou cree une nouvelle entree dans la map, et copie l'addresse pointee par `connection`.
