### ISSUE TITLE
Raw Database data

### ISSUE THREAD

**Issue by pablo-lamtenzan** [ClemaX/ft_irc#47]
We need to be able to share the database using sockets. The database use pointers, so is not possible to just pass it tytes by a socket. We need to pass the values and not the addresses. This problem is not to hard to solve, just need to find a stylish way to share the pointed data.

**Comment by ClemaX** [comment]
Maybe we should have different kind of connections: A normal connection(irc::Client) and RemoteConnection, which is a user on a child or parent irc server and contains data about the server (through reference or pointer) which permits to overload the << operator in the same fashion for all connections, prepend the required `:sender-nick` and relay the serialized message to the destination server.

**Comment by pablo-lamtenzan** [comment]
Yeah, but before that we need to perform a deep copy of the database using sockets (in case the sever connects to another sever). I referenced in #50 that i propose to transfer the data via JSON format. Once all the servers will "share" the database (have an exact intial copy that all instance will be modified at the same time) , we can start to work with the Clients (or Clients class derivations/specialization like your previous proposition).

**Comment by pablo-lamtenzan** [comment]
The database transfer isn't functional yet, but this issue can be closed.
