### ISSUE TITLE
Using Makefile on different OS

### ISSUE THREAD

**Issue by bjacob-56** [ClemaX/ft_irc#9]
The current Makefile doesn't compile on my 42 session. It seems to come from the part where we're looking for openssl.

**Comment by ClemaX** [comment]
Maybe the openssl headers are not sym-linked. Try to run `brew link openssl`.

If this does not work, please show the output of the following command:
`find -L ~/.brew/include -maxdepth 1 -type f -name openssl`

**Comment by bjacob-56** [comment]
It's working with the command `brew link openssl`.
Should we add it to the Makefile ?

**Comment by pablo-lamtenzan** [comment]
I think that won't work on linux machines ...
